#!/bin/sh

# For managing dot files
alias dots="/usr/bin/git --git-dir=$HOME/.dots/ --work-tree=$HOME"

# Info w/ vim keys
alias info="info --vi-keys"

# Trash settings
alias del="trash-put -v"

# Fun fzf stuff
alias pinst="paru -Slq | fzf --multi --preview 'paru -Si {1}' | xargs -ro sudo paru -S"
alias prm="paru -Qq | fzf --multi --preview 'paru -Qi {1}' | xargs -ro sudo paru -Rns"

# Video conferencing
alias vid="firefox -p video $1"

# Verbosity settings
# rm="rm -vI --one-file-system" \
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="echo -E 'Use del, if sure do \\rm'; false" \
    mkd="mkdir -pv"

# Colorize commands
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    egrep="egrep --color=auto" \
    fgrep="fgrep --color=auto" \
    diff="diff --color=auto" \
    ip="ip --color=auto"

# Brevity
alias \
    v="vim" \
    le="less" \
    d="dirs -v" \
    ytdl="youtube-dl"

# ls
alias \
    ll="ls -l" \
    la="ls -A" \
    lla="ls -lA"

