#!/bin/sh

# Default programs
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="st"
export BROWSER="firefox"
export PAGER="less"
export HISTSIZE="INFINITE"
export WM="dwm"
export COLORTERM="truecolor"
export SHELL="zsh"

# ~/ Clean-up
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

export HISTFILE="$XDG_DATA_HOME/history"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GOPATH="$XDG_DATA_HOME/go"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export XORG_LOG="$XDG_DATA_HOME/xorg/xorg.log"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export TEXMFHOME="$XDG_DATA_HOME/texmf"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export TASKDATA="$XDG_DATA_HOME/task"
export TIMEWARRIORDB="$XDG_DATA_HOME/timew"

export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ZDOTDIR="$XDG_CONFIG_HOME/shell/zsh"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export TEXMFCONFIG="$XDG_CONFIG_HOME/texlive/texmf-config"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"
export TASKRC="$XDG_CONFIG_HOME/task/taskrc"
export TASKOPENRC="$XDG_CONFIG_HOME/taskopen/taskopenrc"

export TEXMFVAR="$XDG_CACHE_HOME/texlive/texmf-var"

export LESSHISTFILE="-"
export _JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm
export QT_QPA_PLATFORMTHEME="qt5ct"	# Have QT use gtk2 theme.

# Adds `~/.local/bin` to $PATH
export PATH="$XDG_DATA_HOME/npm-global/bin:$HOME/.local/bin:$PATH"

aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log
pgrep startx >/dev/null || startx "$XINITRC" -- -keeptty &> "$XORG_LOG"

[ -n "$BASH_VERSION" ] && [ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"
