#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[ -f "$XDG_CONFIG_HOME/X11/Xresources" ] && xrdb -merge "$XDG_CONFIG_HOME/X11/Xresources" # Merge resources
[ -f "$XDG_DATA_HOME/bg" ] && setbg "$XDG_DATA_HOME/bg" # Set wallpaper

# Kbd set up
setxkbmap -option caps:swapescape
# setxkbmap -option ctrl:swapcaps_hyper
# xmodmap -e "keycode 9 = Caps_Lock"
# xmodmap -e "keycode 999 = Escape"
xmodmap -e "keycode 199 = Sys_Req"
# xcape -e "Control_L=Escape"

# Fix screen tearing and set up monitors
xrandr --output HDMI-A-0 --set TearFree on
xrandr --output DisplayPort-0 --right-of HDMI-A-0 --set TearFree on

xset s 900                                  # Lock after 15m inactive

statusbar &
xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &      # Compositor
xsidle.sh slock &                           # Lock screen
unclutter &                                 # Unclutter mouse
sxhkd &                                     # Universal bindings
dunst &                                     # Notifications

exec $HOME/.local/bin/startdwm              # exec dwm
